"""Add rent, maintenance, and loan fields

Revision ID: e1fe7e65cf36
Revises: 7f5824fab451
Create Date: 2025-07-13 12:49:54.968760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fe7e65cf36'
down_revision = '7f5824fab451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('monthly_rent', sa.Float(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('tenant_name', sa.String(length=100), nullable=True),
    sa.Column('tenant_phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('issue_description', sa.String(length=255), nullable=False),
    sa.Column('reported_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('receipt_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('repayment_amount', sa.Float(), nullable=True))
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('minute', schema=None) as batch_op:
        batch_op.alter_column('meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('written_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('minute', schema=None) as batch_op:
        batch_op.alter_column('written_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('repayment_amount')
        batch_op.drop_column('interest')

    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('rent_payment')
    op.drop_table('maintenance_request')
    op.drop_table('property')
    # ### end Alembic commands ###
